# Generated by Django 5.2.7 on 2025-10-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_or_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invite_type', models.CharField(choices=[('private_link', 'Private Link'), ('personalized', 'Personalized Email')], max_length=50)),
                ('expiry_date', models.DateTimeField()),
                ('link_limit', models.PositiveIntegerField(default=1)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('invitation_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('ticket_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.ticketclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
