# Generated by Django 4.2 on 2025-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcsvupload',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
