# Generated by Django 5.2.7 on 2025-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_invitation_invitation_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='personal_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
