# Generated by Django 5.2.7 on 2025-10-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
