# Generated by Django 5.2.7 on 2025-10-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_invitation_company_name_invitation_personal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcsvupload',
            name='processed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
