# Generated by Django 4.2 on 2025-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_exportjob_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
