# Generated by Django 5.2.7 on 2025-10-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitationcsvupload_processed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcsvupload',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
