# Generated by Django 5.2.7 on 2025-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_registereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('private_link', 'Private Link'), ('personalized', 'Personalized Email')], default='active', max_length=50),
        ),
    ]
