# Generated by Django 5.2.7 on 2025-10-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
