# Generated by Django 5.2.7 on 2025-10-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_invitation_link_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='title_or_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
