# Generated by Django 5.2.7 on 2025-10-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_alter_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], default='active', max_length=50),
        ),
    ]
